endpointList = ["http://127.0.0.1:26657"]
cosmosRestEndpoint = "https://cosmos-rest.publicnode.com"
logFilePath = ""
gasPrice = "0.005untrn"
taskTicker = 60                                           # seconds
keystorePath = ""
poolAddr = ""
stakeManager = ""
keyName = ""
backendOptions = "file"
runForEntrustedPool = false
