endpointList = ["http://127.0.0.1:26657"]
logFilePath = ""
gasPrice="0.005untrn"
taskTicker = 1  # minutes
keystorePath = ""
poolAddr=""
stakeManager=""
keyName=""
backendOptions="test"
runForEntrustedPool=false